### ISSUE TITLE
msg3d and 2sagcn model

### ISSUE THREAD

**Issue by EdwardTse9944** [NingMa-AI/DASTM#2]
Hi, thanks for your excellent research work. Is there any possibility that you could upload the msg3d and 2s_agcn network python files which could be used in this project?
Thank you so much.

**Comment by NingMa-AI** [comment]
We loaded the two backbones into mmskl folder. Hope it can help you! Not that we do not use the over large full models for all backbones.

**Comment by EdwardTse9944** [comment]
> We loaded the two backbones into mmskl folder. Hope it can help you! Not that we do not use the over large full models for all backbones.

Thank you so much for your response. I believe this will help.
