### ISSUE TITLE
About Processing data

### ISSUE THREAD

**Issue by LLD2** [NingMa-AI/DASTM#6]
Hello, many thanks for the beautiful code you've shared and your outstanding effort. I plan to train the model on other datasets, but I don't know how the three files train_data.npy, train_label.npy, train_frame.npy are obtained, thank you very much!

**Comment by HongyiZhang-1998** [comment]
The obtaining methods of train_data.npy and train_label.npy can be viewed in our appendix Dataset Partition.
train_frame.npy is the number of frames per skeleton sequence, constructed according to your dataset.

**Comment by LLD2** [comment]
Thank you for your response. Could it be that I haven't discovered the appendix because it hasn't been released yet? If you have a moment, could you give me a link. Many thanks again!

**Comment by HongyiZhang-1998** [comment]
It is in this repo, https://github.com/NingMa-AI/DASTM/blob/main/ECCV-appendix.pdf

**Comment by LLD2** [comment]
Thank you for your kind reply! I solved this problem
