### ISSUE TITLE
What do I have to do if I want to train "5-way-5-shot"

### ISSUE THREAD

**Issue by Lululu100** [NingMa-AI/DASTM#7]
Your work is excellent!  If I want to train "5-way-5-shot", what should I do? I refer to the parameter setting of "5-way-1-shot" and set parameter backbones use STGCN, data use NTU-T, SA=1, reg=0.1, num_support_tr=5, num_support_val=5. The accuracy（test acc: 0.8649239775717259） is very different from the accuracy reported in the paper. May I ask if you have encountered similar situations in the training process. Looking forward to your reply.

**Comment by NingMa-AI** [comment]
Thanks for your interest. Your result 0.86 is higher than our reported result 0.83.  My first suggestion is to use multiple seeds and calculate the average performance. As other issues proposed, different seeds may result in significant differences.  
My second suggestion is to change the num_support_val=5 to the default 10. 

If the above two do not work, I suggest following your own results, instead of ours.

**Comment by Lululu100** [comment]
> 

Thank you for your reply. According to your description, is your reported test accuracy performed under the following parameter Settings?
classes_per_it_tr = 5
num_support_tr = 5
num_query_tr = 10
classes_per_it_val = 5
num_support_val = 10
num_query_val = 10
I will try again to train the network under this parameter.

**Comment by Lululu100** [comment]
Hello. May I ask whether 5way1shot and 5way5shot are carried out in the same experimental environment (seed)? In my environment, when seed=7, 5way1shot and paper report decreased slightly, but 5way5shot and paper report accuracy improved a lot. Looking forward to your reply.

**Comment by NingMa-AI** [comment]
> Hello. May I ask whether 5way1shot and 5way5shot are carried out in the same experimental environment (seed)? In my environment, when seed=7, 5way1shot and paper report decreased slightly, but 5way5shot and paper report accuracy improved a lot. Looking forward to your reply.

Yes! We used the same seeds.

**Comment by Lululu100** [comment]
Hello. I tried testing it with multiple seeds, and it worked well. Do I need to change the segment in nturgbd_dataset.py when I want to change the dataset for training, for example, set segment=60 when using ntu-s and segment=100 when using kinetics?In addition, does the parameter num_class in the graph convolutional network need to be transformed for the 5way5shot and 5way1shot tasks? I have learned a lot during the communication with you, which is very helpful to me. I am looking forward to your reply.

**Comment by NingMa-AI** [comment]
1. ”does the parameter num_class in the graph convolutional network need to be transformed for the 5way5shot and 5way1shot tasks? “    

2. "Do I need to change the segment in nturgbd_dataset.py when I want to change the dataset for training, for example, set segment=60 when using ntu-s and segment=100 when using kinetics?"

 They are not necessary. Thanks for your interest.

**Comment by Lululu100** [comment]
Thank you very much for your reply. I have clearly understood your parameter Settings from your communication. Looking forward to more work from you.
