### ISSUE TITLE
Issue about the two key points for action recognition in the process of processing the data set.

### ISSUE THREAD

**Issue by GoodMorningAndGoodEvening** [NingMa-AI/DASTM#9]
Hi, your work is very innovative! May I ask if you have considered the two key points for action recognition in the process of processing the data set: different individuals perform the same/different actions, and the same individuals perform the same/different actions under different perspectives? I look forward to receiving your reply, thank you very much.

**Comment by NingMa-AI** [comment]
Thanks for your interest, we haven't considered the above two problems.

**Comment by GoodMorningAndGoodEvening** [comment]
Thank you very much for your answer. I have a small question: the description process of the NTU-RGB+D dataset includes the number of categories and performers. May I ask if you randomly select samples or select samples from the same perspective or performer when using data evaluation？

**Comment by NingMa-AI** [comment]
Yes, the samples are randomly selected.

**Comment by GoodMorningAndGoodEvening** [comment]
Thank you very much for your reply, it helps me understand the problem. I wish you a smooth work and a happy life! thank you.
